DEF_TREE_STATUS(OK,                                 "OK")

DEF_TREE_STATUS(ERROR_VERIFY,                       "ERROR_VERIFY")

DEF_TREE_STATUS(WARNING_LEFT_CHILD_IS_OCCUPIED,     "WARNING_LEFT_CHILD_IS_OCCUPIED")

DEF_TREE_STATUS(WARNING_RIGHT_CHILD_IS_OCCUPIED,    "WARNING_RIGHT_CHILD_IS_OCCUPIED")

DEF_TREE_STATUS(ERROR_MEM_ALLOC,                    "ERROR_MEM_ALLOC")

DEF_TREE_STATUS(WARNING_REQUEST_TO_DEL_NULL_NODE,   "WARNING_REQUEST_TO_DEL_NULL_NODE")

DEF_TREE_STATUS(WARNING_REQUEST_TO_DEL_NOT_A_LEAF,  "WARNING_REQUEST_TO_DEL_NOT_A_LEAF")
