DEF_TREE_STATUS(OK,                                 "OK")

DEF_TREE_STATUS(ERROR_VERIFY,                       "ERROR_VERIFY")

DEF_TREE_STATUS(WARNING_LEFT_CHILD_IS_OCCUPIED,     "WARNING_LEFT_CHILD_IS_OCCUPIED")

DEF_TREE_STATUS(WARNING_RIGHT_CHILD_IS_OCCUPIED,    "WARNING_RIGHT_CHILD_IS_OCCUPIED")

DEF_TREE_STATUS(ERROR_MEM_ALLOC,                    "ERROR_MEM_ALLOC")

DEF_TREE_STATUS(WARNING_REQUEST_TO_DEL_NULL_NODE,   "WARNING_REQUEST_TO_DEL_NULL_NODE")

DEF_TREE_STATUS(WARNING_REQUEST_TO_DEL_NOT_A_LEAF,  "WARNING_REQUEST_TO_DEL_NOT_A_LEAF")

DEF_TREE_STATUS(WARNING_ROOT_ALREADY_EXISTS,        "WARNING_ROOT_ALREADY_EXISTS")

DEF_TREE_STATUS(ERROR_MAX_DUMP_PATH_LEN_TOO_SHORT,  "ERROR_MAX_DUMP_PATH_LEN_TOO_SHORT")

DEF_TREE_STATUS(ERROR_CANT_CREATE_DUMP_DIR,         "ERROR_CANT_CREATE_DUMP_DIR")

DEF_TREE_STATUS(ERROR_CANT_OPEN_DUMP_FILE,          "ERROR_CANT_OPEN_DUMP_FILE")

DEF_TREE_STATUS(ERROR_TOO_LONG_CMD_GEN_DUMP_IMG,    "ERROR_TOO_LONG_CMD_GEN_DUMP_IMG")
